#config_version=6
mode:
  start_events: ball_starting
  priority: 100
    

slide_player:
  mode_base_started: base    
        
        
variable_player:
    s-left-sling_active:
        score: 100
    s-right-sling_active:
        score: 100
    s-popbumper-1_active:
        score: 100
    s-popbumper-2_active:
        score: 100
    s-popbumper-3_active:        
        score: 100    

    s-toplane1_active:
        score: 100
    s-toplane2_active:
        score: 100
    s-toplane3_active:
        score: 100      
    s-bottomlane1_active:
        score: 100
    s-bottomlane2_active:
        score: 100
    s-bottomlane3_active:
        score: 100
    s-bottomlane4_active:
        score: 100
    s-bottomlane5_active:
        score: 100


    
        